import uuid
from datetime import datetime, timezone
from enum import Enum as PyEnum

from sqlalchemy import (
    Boolean,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.sql import func

from app.db.session import Base


# --------------------------------------------------------------------------- #
#  Helpers                                                                      #
# --------------------------------------------------------------------------- #

def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def new_uuid() -> uuid.UUID:
    return uuid.uuid4()


# --------------------------------------------------------------------------- #
#  Enums (stored as VARCHAR in DB for readability in raw SQL queries)          #
# --------------------------------------------------------------------------- #

class SenderType(str, PyEnum):
    USER  = "USER"   # inbound message from WhatsApp user
    BOT   = "BOT"    # outbound message generated by LLM
    AGENT = "AGENT"  # outbound message typed manually by a human operator

class MessageStatus(str, PyEnum):
    SENT      = "SENT"
    DELIVERED = "DELIVERED"
    READ      = "READ"
    FAILED    = "FAILED"

class ConversationStatus(str, PyEnum):
    OPEN    = "OPEN"
    CLOSED  = "CLOSED"
    PENDING = "PENDING"  # waiting for agent review


# --------------------------------------------------------------------------- #
#  Contacts                                                                     #
# --------------------------------------------------------------------------- #

class Contact(Base):
    """
    One row per unique WhatsApp user (identified by wa_id = phone number).
    Created automatically on first inbound message.
    """
    __tablename__ = "contacts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    wa_id: Mapped[str] = mapped_column(
        String(20), nullable=False, unique=True, index=True,
        comment="WhatsApp ID — E.164 phone number without the + sign"
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    phone_number: Mapped[str | None] = mapped_column(String(20), nullable=True)
    is_blocked: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False
    )

    # Relationships
    conversations: Mapped[list["Conversation"]] = relationship(
        back_populates="contact", cascade="all, delete-orphan"
    )

    tenant: Mapped["Tenant"] = relationship(back_populates="contacts")

    def __repr__(self) -> str:
        return f"<Contact wa_id={self.wa_id} name={self.name}>"
    



# --------------------------------------------------------------------------- #
#  Conversations                                                                #
# --------------------------------------------------------------------------- #

class Conversation(Base):
    """
    Groups messages with a single contact into a conversation thread.
    One contact can have multiple conversations over time (e.g. re-opened).

    The is_bot_active flag is the core of Phase 5 human-in-the-loop control.
    When False, the webhook handler skips LLM processing for this conversation.
    """
    __tablename__ = "conversations"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    contact_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("contacts.id", ondelete="CASCADE"),
        nullable=False, index=True
    )

    status: Mapped[ConversationStatus] = mapped_column(
        Enum(ConversationStatus, name="conversation_status_enum"),
        default=ConversationStatus.OPEN,
        nullable=False,
    )

    # ------------------------------------------------------------------ #
    #  Bot control — SOURCE OF TRUTH for human-in-the-loop               #
    # ------------------------------------------------------------------ #
    is_bot_active: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False,
        comment="When False, AI processing is skipped. Operator handles manually."
    )

    # Optional: which human agent is handling this if bot is paused
    assigned_agent_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), nullable=True
    )

    # System prompt override for this specific conversation
    system_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Denormalised for fast sidebar sorting — updated on every new message
    last_message_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True, index=True
    )
    last_message_preview: Mapped[str | None] = mapped_column(
        String(255), nullable=True
    )
    unread_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False
    )

    # Relationships
    contact: Mapped["Contact"] = relationship(back_populates="conversations")
    messages: Mapped[list["Message"]] = relationship(
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="Message.created_at",
    )

    __table_args__ = (
        Index("ix_conversations_contact_last_msg", "contact_id", "last_message_at"),
    )

    def __repr__(self) -> str:
        return f"<Conversation id={self.id} bot_active={self.is_bot_active}>"


# --------------------------------------------------------------------------- #
#  Messages                                                                     #
# --------------------------------------------------------------------------- #

class Message(Base):
    """
    Every single message — inbound and outbound — is stored here.
    This is the append-only log. Nothing is ever deleted.

    sender_type distinguishes whether the message came from:
      USER  = WhatsApp user (inbound)
      BOT   = AI-generated reply (outbound)
      AGENT = Human operator reply via dashboard (outbound)
    """
    __tablename__ = "messages"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    conversation_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # The wamid Meta assigns to every message (e.g. wamid.HBgLMTIzNDU2Nzg5...)
    # Nullable because BOT/AGENT messages get this assigned after Meta ACKs
    meta_message_id: Mapped[str | None] = mapped_column(
        String(255), nullable=True, unique=True, index=True
    )

    sender_type: Mapped[SenderType] = mapped_column(
        Enum(SenderType, name="sender_type_enum"),
        nullable=False,
        index=True,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_type: Mapped[str] = mapped_column(
        String(50), default="text", nullable=False,
        comment="text | image | audio | document | interactive"
    )

    status: Mapped[MessageStatus] = mapped_column(
        Enum(MessageStatus, name="message_status_enum"),
        default=MessageStatus.SENT,
        nullable=False,
    )

    # Timestamps
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False, index=True
    )
    delivered_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    read_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # Relationship
    conversation: Mapped["Conversation"] = relationship(back_populates="messages")

    __table_args__ = (
        Index("ix_messages_conversation_created", "conversation_id", "created_at"),
    )

    def __repr__(self) -> str:
        return f"<Message id={self.id} type={self.sender_type} status={self.status}>"


# --------------------------------------------------------------------------- #
#  BotConfig                                                                    #
# --------------------------------------------------------------------------- #

class BotConfig(Base):
    """
    Global bot configuration — one row for the whole system.
    Use get_or_create pattern; never insert more than one row.
    """
    __tablename__ = "bot_config"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, default=1)
    default_system_prompt: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        default=(
            "You are a helpful WhatsApp business assistant. "
            "Be concise, friendly, and professional. "
            "Keep replies under 3 sentences unless the user asks for detail."
        ),
    )
    max_context_messages: Mapped[int] = mapped_column(
        Integer, default=20, nullable=False
    )
    is_globally_active: Mapped[bool] = mapped_column(
        Boolean, default=True, nullable=False
    )

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False
    )

    __table_args__ = (
        UniqueConstraint("id", name="uq_bot_config_singleton"),
    )

# --------------------------------------------------------------------------- #
#  Paste this at the BOTTOM of app/db/models.py                               #
# --------------------------------------------------------------------------- #

class TenantStatus(str, PyEnum):
    ACTIVE   = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"

class UserRole(str, PyEnum):
    SUPER_ADMIN = "SUPER_ADMIN"  # tum — full platform control
    TENANT_ADMIN = "TENANT_ADMIN"  # client — sirf apna data


class Tenant(Base):
    """
    Har client ek Tenant hai.
    Ek tenant = ek WhatsApp number = ek business.
    """
    __tablename__ = "tenants"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    business_name: Mapped[str] = mapped_column(String(255), nullable=False)
    owner_email: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True
    )

    # Meta credentials — har client ke apne
    phone_number_id: Mapped[str] = mapped_column(
        String(50), nullable=False, unique=True, index=True,
        comment="Meta phone_number_id — webhook routing ke liye"
    )
    whatsapp_number: Mapped[str] = mapped_column(String(20), nullable=False)
    meta_access_token: Mapped[str] = mapped_column(Text, nullable=False)

    # n8n bot webhook — yahan forward karenege inbound messages
    n8n_webhook_url: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Limits — tum set karo per client
    monthly_message_limit: Mapped[int] = mapped_column(
        Integer, default=1000, nullable=False
    )
    current_month_messages: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False
    )

    status: Mapped[TenantStatus] = mapped_column(
        Enum(TenantStatus, name="tenant_status_enum"),
        default=TenantStatus.ACTIVE,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, onupdate=utcnow, nullable=False
    )

    # Relationships
    users: Mapped[list["TenantUser"]] = relationship(
        back_populates="tenant", cascade="all, delete-orphan"
    )
    contacts: Mapped[list["Contact"]] = relationship(
        back_populates="tenant", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Tenant {self.business_name} | {self.whatsapp_number}>"


class TenantUser(Base):
    """
    Platform users — Super Admin ya Tenant Admin.
    Ek tenant ke multiple users ho sakte hain (e.g. multiple operators).
    """
    __tablename__ = "tenant_users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    tenant_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=True,  # Super Admin ka koi tenant nahi hota
        index=True,
    )
    email: Mapped[str] = mapped_column(
        String(255), nullable=False, unique=True, index=True
    )
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)
    role: Mapped[UserRole] = mapped_column(
        Enum(UserRole, name="user_role_enum"),
        nullable=False,
        default=UserRole.TENANT_ADMIN,
    )
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=utcnow, nullable=False
    )

    # Relationships
    tenant: Mapped["Tenant | None"] = relationship(back_populates="users")

    def __repr__(self) -> str:
        return f"<TenantUser {self.email} | {self.role}>"


class APIUsage(Base):
    """
    Har message ka record — limit tracking ke liye.
    Tum dekh sako kaunsa client kitne messages use kar raha hai.
    """
    __tablename__ = "api_usage"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=new_uuid
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    month: Mapped[str] = mapped_column(
        String(7), nullable=False,
        comment="Format: 2024-01 — monthly bucketing ke liye"
    )
    message_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    inbound_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    outbound_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    __table_args__ = (
        UniqueConstraint("tenant_id", "month", name="uq_api_usage_tenant_month"),
        Index("ix_api_usage_tenant_month", "tenant_id", "month"),
    )