"""add_reset_token_to_users

Revision ID: aff99b18139b
Revises: d4cee9397a5e
Create Date: 2026-05-18 14:18:05.224548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff99b18139b'
down_revision: Union[str, None] = 'd4cee9397a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_usage', 'month',
               existing_type=sa.VARCHAR(length=7),
               comment='Format: 2024-01 monthly bucketing ke liye',
               existing_comment='Format: 2024-01 — monthly bucketing ke liye',
               existing_nullable=False)
    op.alter_column('contacts', 'wa_id',
               existing_type=sa.VARCHAR(length=20),
               comment='WhatsApp ID E.164 phone number without the + sign',
               existing_comment='WhatsApp ID — E.164 phone number without the + sign',
               existing_nullable=False)
    op.alter_column('contacts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('tenant_users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('tenant_users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_tenant_users_reset_token'), 'tenant_users', ['reset_token'], unique=False)
    op.alter_column('tenants', 'phone_number_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Meta phone_number_id webhook routing ke liye',
               existing_comment='Meta phone_number_id — webhook routing ke liye',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'phone_number_id',
               existing_type=sa.VARCHAR(length=50),
               comment='Meta phone_number_id — webhook routing ke liye',
               existing_comment='Meta phone_number_id webhook routing ke liye',
               existing_nullable=False)
    op.drop_index(op.f('ix_tenant_users_reset_token'), table_name='tenant_users')
    op.drop_column('tenant_users', 'reset_token_expires')
    op.drop_column('tenant_users', 'reset_token')
    op.alter_column('contacts', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contacts', 'wa_id',
               existing_type=sa.VARCHAR(length=20),
               comment='WhatsApp ID — E.164 phone number without the + sign',
               existing_comment='WhatsApp ID E.164 phone number without the + sign',
               existing_nullable=False)
    op.drop_constraint('uq_bot_config_singleton', 'bot_config', type_='unique')
    op.alter_column('api_usage', 'month',
               existing_type=sa.VARCHAR(length=7),
               comment='Format: 2024-01 — monthly bucketing ke liye',
               existing_comment='Format: 2024-01 monthly bucketing ke liye',
               existing_nullable=False)
    # ### end Alembic commands ###
