"""add_tenants_auth

Revision ID: d4cee9397a5e
Revises: 663397bdc572
Create Date: 2026-05-06 23:52:40.720805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cee9397a5e'
down_revision: Union[str, None] = '663397bdc572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=False),
    sa.Column('phone_number_id', sa.String(length=50), nullable=False, comment='Meta phone_number_id — webhook routing ke liye'),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=False),
    sa.Column('meta_access_token', sa.Text(), nullable=False),
    sa.Column('n8n_webhook_url', sa.Text(), nullable=True),
    sa.Column('monthly_message_limit', sa.Integer(), nullable=False),
    sa.Column('current_month_messages', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='tenant_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_owner_email'), 'tenants', ['owner_email'], unique=True)
    op.create_index(op.f('ix_tenants_phone_number_id'), 'tenants', ['phone_number_id'], unique=True)
    op.create_table('api_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False, comment='Format: 2024-01 — monthly bucketing ke liye'),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('inbound_count', sa.Integer(), nullable=False),
    sa.Column('outbound_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'month', name='uq_api_usage_tenant_month')
    )
    op.create_index(op.f('ix_api_usage_tenant_id'), 'api_usage', ['tenant_id'], unique=False)
    op.create_index('ix_api_usage_tenant_month', 'api_usage', ['tenant_id', 'month'], unique=False)
    op.create_table('tenant_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_users_email'), 'tenant_users', ['email'], unique=True)
    op.create_index(op.f('ix_tenant_users_tenant_id'), 'tenant_users', ['tenant_id'], unique=False)
    # op.create_unique_constraint('uq_bot_config_singleton', 'bot_config', ['id'])
    op.add_column('contacts', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'contacts', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_column('contacts', 'tenant_id')
    op.drop_constraint('uq_bot_config_singleton', 'bot_config', type_='unique')
    op.drop_index(op.f('ix_tenant_users_tenant_id'), table_name='tenant_users')
    op.drop_index(op.f('ix_tenant_users_email'), table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index('ix_api_usage_tenant_month', table_name='api_usage')
    op.drop_index(op.f('ix_api_usage_tenant_id'), table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_tenants_phone_number_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_owner_email'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
